package parser

// DebugLogEntry represents a debug log entry
type DebugLogEntry struct {
	Pattern Pattern
	At      Cursor
	Level   uint
	Matched bool
}

// DebugProfile represents a debug-profile generated by Parser.Debug
type DebugProfile struct {
	Log []*DebugLogEntry
}

func newDebugProfile() *DebugProfile {
	return &DebugProfile{
		Log: make([]*DebugLogEntry, 0),
	}
}

func (dp *DebugProfile) record(
	pattern Pattern,
	at Cursor,
	level uint,
) int {
	if dp == nil {
		return -1
	}

	dp.Log = append(dp.Log, &DebugLogEntry{
		Pattern: pattern,
		At:      at,
		Level:   level,
		Matched: true,
	})
	return len(dp.Log) - 1
}

func (dp *DebugProfile) markMismatch(index int) {
	if dp == nil {
		return
	}
	dp.Log[index].Matched = false
}
